MAX_GROUP_LEN = 5
MAX_GROUP_DATE_DIFF = 60
MAX_MOV_DAYS_BEFORE_INV = 14
MAX_MOV_DAYS_AFTER_INV = 90
MAX_REL_AMOUNT_DIFF = 0.03
GAUSSIAN_SIMILARITY_SCALE = 0.001
WINDOW_SIZE = 3
AMOUNT_BIN = 100000

SIMILARITY_WEIGHT = 1
SIZE_WEIGHT = 1
DATE_WEIGHT = 1


